/* eslint-disable react/prop-types */
import React from 'react';

import { Inter } from 'next/font/google';

import './globals.css';
import Navbar from '@/components/parts/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-screen min-h-screen bg-white`}>
        <Navbar />
        <div className="container mx-auto size-full px-4 py-5">{children}</div>
      </body>
    </html>
  );
}
